services:
  postgres:
    image: 'postgres:latest'
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/csv:/csv
      - ~/db:/db
  #pgadmin4
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@email.com
      PGADMIN_DEFAULT_PASSWORD: 123
  python:
    image: python:3.9
    container_name: pythonapp
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - ~/db:/db  # Mounts the local "db" directory into "/db" inside the container
    working_dir: /db 
    command: ["python", "db.py"]